
import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Button } from '../common/Button';
// LyriaControls and Lyria types imports removed

interface InfoModalProps {
  isOpen: boolean;
  onClose: () => void;
  // Lyria-related props removed
}

const markdownContent = `
# Logisticore: Game Guide

## 1. Game Objective
The primary goal in Logisticore is to achieve strategic supremacy by controlling key territories and outmaneuvering your opponent. Victory can typically be achieved by:
- Capturing and holding all enemy Command Nodes (CN).
- Reaching the maximum turn limit (default: 60) with a dominant strategic position (rules for this may vary).

## 2. Core Game Loop (Phases)
The game progresses in turns, with each turn divided into several phases:

1.  **FLUCTUATION:** AI factions assess the situation and generate new Operational Plans (OpPlans).
2.  **RESOURCE:** Factions collect Quantum (QR) and Materiel (MAT) from nodes they control.
3.  **MANEUVER (AXIOM):** AXIOM faction performs actions (deploy, move, attack, fortify).
4.  **MANEUVER (GEM-Q):** GEM-Q faction performs actions.
5.  **COMBAT:** Battles are resolved in nodes where opposing forces meet.
6.  **UPKEEP:** Factions pay MAT to maintain their units and fortified nodes. Units may be disbanded if MAT is insufficient.

## 3. Resources
-   **Quantum (QR):** Abstract resource, primarily used for advanced actions or future features (currently accumulates). Generated by CN and QN nodes.
-   **Materiel (MAT):** Primary resource for building units, fortifications, and paying upkeep. Generated mainly by Industrial Hubs and other specific nodes.

## 4. Key Node Types
-   **CN (Command Node):** Your faction's headquarters. Essential for deploying new units. Losing all CNs results in defeat. Generates QR and some MAT. Max units: 35.
-   **INDUSTRIAL_HUB:** Primary source of MAT. Strategically vital for economic strength. Max units: 20. MAT Output: 20.
-   **FORTRESS:** Highly defensible node, provides significant combat bonuses to defenders. Generates some QR and MAT. Max units: 40.
-   **URBAN:** Represents cities or dense areas. Provides moderate MAT. Max units: 20. MAT Output: 10.
-   **STANDARD:** Generic nodes, may provide some MAT. Max units: 20.
-   **(WG) West Gate / (EG) East Gate:** Special standard nodes, often tactically important due to connections. Shaped as diamonds.
-   **RECON_ARRAY:** Hexagonal node used for the reconnaissance system. Does not generate resources but enables intelligence gathering capabilities.

## 5. Basic Controls & UI Elements

### Header:
-   **LOGISTICORE Title:** Game title.
-   **Map Controls (Center):** Zoom In, Zoom Out, Reset View.
-   **Game Controls (Right):**
    -   **NEW SETUP:** Resets the game to its initial state.
    -   **PLAY/PAUSE (RUNNING/PAUSED):** Toggles the game progression.
    -   **Lyria Button (Music Note):** Controls the Lyria Music Engine. Play/Pause music stream. Red indicates an error.
    -   **Data Icon (Floppy Disk):** Opens Save/Load Game modal.
    -   **Settings Icon (Cog):** Opens the Settings modal (which includes access to this Game Guide).

### Map Area:
-   **Nodes:** Click to select and view details in the bottom panel. Double-click to zoom to the node.
    -   **Circles:** Standard, Fortress, CN nodes.
    -   **Diamonds:** Urban, Industrial Hubs, WG, EG.
    -   **Hexagons:** Recon Array nodes.
    -   **Number inside Node:** Standard units present.
    -   **Small Shield Icon (Top-right of node):** Fortification level.
    -   **Artillery Icon (Bottom-right of node):** Number of artillery pieces.
-   **Connections:** Lines between nodes show valid movement paths. Color may indicate ownership of connected nodes.

### Bottom Panels (Below Map):
1.  **Node Activity Display / Strategic Attrition Report:**
    -   **Node Details (When a node is selected):** Shows specific information about the selected node (owner, units, resources, status).
    -   **Strategic Attrition Report (Default):** Displays key performance indicators (KPIs) for both factions, cycling through pages of metrics.
2.  **OpPlan Panels (AXIOM & GEM-Q):**
    -   Displays the current Operational Plan for each AI faction, including their objective, operation name, and specific tasks.
    -   **HISTORY button:** Opens a modal showing past OpPlans for that faction.

### Right Sidebar:
-   **Turn Information:** Current turn, active player/system, current phase, and timers.
-   **Faction Overview (AXIOM & GEM-Q):** Summary of each faction's resources and force composition. Includes Recon capability.
-   **System Log:** Chronological list of game events. Expandable and copyable.
-   **Battle History:** List of past battles. Click an entry to open a detailed Battle Report Modal.

## 6. Attrition Report Metrics
The Strategic Attrition Report shows these metrics:
*   **Units Deployed/Lost Ratio, Battles Won/Lost, Combat Success Rate, Nodes Held, Current MAT, MAT Efficiency (MER), Force Projection Cost (FPC), Attrition Endurance (AEI), Territorial Econ Value (TEV).**
*   **Reconnaissance KPIs (New Page):** Active Recon Arrays, Pulses Used, Intel Advantage Turns, QR/MAT Spent on Recon.
*   **Advanced Attrition KPIs (New Page):** Supply System Stress (SSS), Fortification Focus, Offensive Success (OSR), Strategic Denial (SRDI), Blood Price of Territory, Combat Overkill Index.

## 7. Combat System
-   Combat occurs when units move into an enemy/neutral node.
-   **Artillery Phase:** Before direct combat, artillery may fire.
    -   **Offensive Support:** Attacker's artillery from staging node can fire.
    -   **Defensive Support:** Defender's artillery on the contested node can fire.
    -   Artillery fire costs MAT and inflicts casualties before ground engagement. Fortification can reduce artillery damage.
-   **Ground Combat:** Round-based. Dice rolls based on unit counts, modified by fortifications, low supply, etc. Higher roll inflicts a casualty. Continues until one side is eliminated or max rounds.
-   Node capture if attacker wins. Stalemate results in attacker retreat.

## 8. Reconnaissance System
-   Capture \`RECON_ARRAY\` nodes.
-   Pay a one-time QR & MAT cost to **activate** an owned \`RECON_ARRAY\` via AI Action. It must be connected to your Command Node network.
-   Activated arrays incur a small MAT upkeep per turn to maintain *capability*.
-   If you have a capable array, use the \`PERFORM_RECON_PULSE\` AI Action (costs QR & MAT) targeting one of your active arrays.
-   A **Recon Pulse** grants full, live map vision for your current turn only. This intel is reflected in AI's \`mapSummary\`.
-   Without a pulse, AI vision is limited to owned nodes + adjacent (Fog of War). Enemy faction stats are from the previous turn's snapshot.

## 9. Lyria Music Engine
-   Dynamic, AI-powered music generation.
-   Control via the Lyria button in the header (Play/Pause stream).
-   Access Lyria Music Engine controls within the main **Game Settings** modal. Adjust music prompts, their weights, and advanced parameters like BPM, temperature, scale, etc. Save/Load configurations.

## 10. Low Supply & Materiel Shortages
-   If MAT is 0 or less after Upkeep, all faction nodes enter 'Low Supply'.
-   'Low Supply' nodes: No MAT output, units suffer combat penalties.
-   Negative MAT after upkeep triggers automatic unit disbandment.
`;

const InfoModal: React.FC<InfoModalProps> = ({ 
  isOpen, 
  onClose,
  // Lyria-related props removed
}) => {
  if (!isOpen) return null;

  // showLyriaControls state and related logic removed

  return (
    <div 
      className="fixed inset-0 z-[60] flex items-center justify-center bg-black bg-opacity-85"
      onClick={onClose} 
    >
      <div 
        className="bg-terminal-gray-darker text-terminal-gray-light terminal-border w-[95vw] h-[90vh] max-w-4xl rounded-lg shadow-xl flex flex-col"
        onClick={(e) => e.stopPropagation()} 
      >
        <div className="flex items-center justify-between p-4 border-b border-terminal-green border-opacity-30 flex-shrink-0">
          <h2 className="text-2xl font-semibold text-terminal-green">Game Guide & Information</h2>
          <button
            onClick={onClose}
            className="text-terminal-gray-light hover:text-terminal-red text-3xl"
            aria-label="Close game guide"
          >
            &times;
          </button>
        </div>
        <div className="p-6 overflow-y-auto flex-1 prose prose-sm md:prose-base prose-invert max-w-none 
                        prose-headings:text-terminal-cyan prose-h1:text-2xl prose-h1:mb-3 prose-h2:text-xl prose-h2:mt-4 prose-h2:mb-2
                        prose-strong:text-terminal-yellow prose-ul:list-disc prose-ul:ml-5 prose-li:my-0.5
                        prose-table:border prose-table:border-terminal-gray prose-th:border prose-th:border-terminal-gray prose-th:p-2 prose-td:border prose-td:border-terminal-gray prose-td:p-2
                        prose-a:text-terminal-blue hover:prose-a:text-blue-400
                        prose-code:bg-terminal-gray-dark prose-code:p-0.5 prose-code:rounded-sm prose-code:text-xs prose-code:text-terminal-red">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {markdownContent}
          </ReactMarkdown>
          
          {/* Lyria controls button and panel removed from here */}

        </div>
         <div className="p-3 border-t border-terminal-green border-opacity-30 text-right flex-shrink-0">
            <Button 
                onClick={onClose}
                className="px-4 py-2 bg-terminal-green text-black font-semibold rounded hover:bg-green-400 transition-colors"
            >
                Close Guide
            </Button>
        </div>
      </div>
    </div>
  );
};

export default InfoModal;
